---
name: mailgun
channels:
  - defaults
dependencies:
  - python >=3.11
  # build & host deps
  - pip
  # runtime deps
  - requests >=2.32.5
  - conda-forge::httpx2 >=2.7.0
  - httpx >=0.24.0
  # tests
  - pytest >=9.0.3
  # other
  - pre-commit
  - toml
