---
name: mailgun-dev
channels:
  - defaults
dependencies:
  - python >=3.11
  # build & host deps
  - pip
  - setuptools-scm
  # PyPi only
  - python-build
  # runtime deps
  - requests >=2.32.5
  - conda-forge::httpx2 >=2.7.0
  - httpx >=0.24.0
  - typing_extensions >=4.7.1  # [py<311]
  # extras
  - fastapi
  # tests
  - conda-forge::pyfakefs
  - coverage >=4.5.4
  - hypothesis
  - openssl
  - pytest >=9.0.3
  - pytest-asyncio
  - pytest-benchmark
  - pytest-cov >=5.0.0
  - pytest-xdist
  - responses
  # linters, formatters & typing
  - make
  - mypy
  - pyright
  - ruff
  - toml
  - types-requests >=2.33.0
  # other
  - conda
  - jsonschema
  - pre-commit
  - python-dotenv >=0.19.2
  - types-jsonschema
  - pip:
      # Requires llvm; disabled on CI
      #- atheris >=2.3.0
      - bandit
      - codecov >=2.0.16
      - docconvert
      - pystra
      - pyment >=0.3.3
      - pytest-order
      - scalene >=1.3.16
      - snakeviz
      - typos
      - vulture
      - wily >=1.2
      # PyPI
      - twine
