"""Mailgun API Routes Configuration."""

EXACT_ROUTES = {
    "messages": ["v3", ["messages"]],
    "mimemessage": ["v3", ["messages.mime"]],
    "resend_message": ["v3", ["resendmessage"]],
    "ippools": ["v3", ["ip_pools"]],
    "dkim_keys": ["v1", ["dkim", "keys"]],
    "dkim": ["v1", ["dkim", "keys"]],
    "domainlist": ["v4", ["domainlist"]],
    "analytics": ["v1", ["analytics", "usage", "metrics", "logs", "tags", "limits"]],
    "bounce_classification": ["v2", ["bounce-classification", "metrics"]],
    "users": ["v5", ["users", "me"]],
    "subaccount_ip_pools": ["v5", ["accounts", "subaccounts", "ip_pools"]],
    "subaccount_ip_pool": ["v5", ["accounts", "subaccounts", "{subaccountId}", "ip_pool"]],
    "dkim_management_rotation": ["v1", ["dkim_management", "domains", "{name}", "rotation"]],
    "dkim_management_rotate": ["v1", ["dkim_management", "domains", "{name}", "rotate"]],
    "account_templates": ["v4", ["templates"]],
    "account_webhooks": ["v1", ["webhooks"]],
}

PREFIX_ROUTES = {
    "templates": ["v3", "", None],
    "analytics": ["v1", "", None],
    "bounceclassification": ["v2", "", "bounce-classification"],
    "addressvalidate": ["v4", "address/validate", None],
    "addressparse": ["v4", "address/parse", None],
    "address": ["v4", "address", None],
    "inbox": ["v4", "inbox", None],
    "inspect": ["v4", "inspect", None],
    "spamtraps": ["v3", "spamtraps", None],
    "blocklists": ["v3", "blocklists", None],
    "reputation": ["v3", "reputation", None],
    "users": ["v5", "", None],
    "keys": ["v1", "", None],
    "webhooks": ["v1", "", None],
    "thresholds": ["v1", "", None],
    "alerts": ["v1", "", None],
    "accounts": ["v5", "", None],
    "sandbox": ["v5", "", None],
    "x509": ["v2", "", None],
    "ip_whitelist": ["v2", "", None],
    "events": ["v3", "", None],
    "tags": ["v3", "", None],
    "bounces": ["v3", "", None],
    "unsubscribes": ["v3", "", None],
    "complaints": ["v3", "", None],
    "whitelists": ["v3", "", None],
    "routes": ["v3", "", None],
    "lists": ["v3", "", None],
    "mailboxes": ["v3", "", None],
    "stats": ["v3", "", None],
    "ips": ["v3", "", None],
    "ip_pools": ["v3", "", None],
}

DOMAIN_ALIASES = {
    "dkimauthority": "dkim_authority",
    "dkimselector": "dkim_selector",
    "webprefix": "web_prefix",
    "sendingqueues": "sending_queues",
}

# Grouping domain endpoints by API version
DOMAIN_ENDPOINTS = {
    "v1": ["security"],
    "v3": [
        "connection",
        "tracking",
        "dkim_authority",
        "dkim_selector",
        "web_prefix",
        "sending_queues",
        "credentials",
        "templates",
        "mailboxes",
        "ips",
        "pool",
        "dynamic_pools",
        "bounces",
        "unsubscribes",
        "complaints",
        "whitelists",
        "webhooks",
    ],
    "v4": ["domains", "verify"],
}
