name: Build and Publish Python distributions to TestPyPI and PyPI

on:
  workflow_run:
    workflows: [ "CI" ]
    types:
      - completed
    branches:
      - main
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build-and-publish:
    # Only run if the dependent workflow succeeded or this was triggered by tags/manual
    if: |
      (github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success') ||
      github.event_name == 'push' ||
      github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    # No need for id-token permission with token-based auth
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Required for setuptools-scm

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build
          pip install -e .

      - name: Build package
        run: python -m build

      - name: Publish to TestPyPI
        if: github.event_name == 'workflow_dispatch' || startsWith(github.ref, 'refs/tags/v')
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
          password: ${{ secrets.TEST_PYPI_API_TOKEN }}
          # TODO: Disable trusted publishing. Fix it later.
          verify-metadata: false
          verbose: true
          skip-existing: true

#      - name: Publish to PyPI
#        if: startsWith(github.ref, 'refs/tags/v')
#        uses: pypa/gh-action-pypi-publish@release/v1
#        with:
#          password: ${{ secrets.PYPI_API_TOKEN }}
